// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTZMqNGZ7KpPwEX_3_hY-B6Kcc0leFySI',
    appId: '1:604553621995:web:679204b48eb2d4fe28e9ae',
    messagingSenderId: '604553621995',
    projectId: 'uni-cronos-7216',
    authDomain: 'uni-cronos-7216.firebaseapp.com',
    storageBucket: 'uni-cronos-7216.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-RMI-VXgNY3tg1ibSl4eQGYiDHV4zZSI',
    appId: '1:604553621995:android:06298bf76d98af0028e9ae',
    messagingSenderId: '604553621995',
    projectId: 'uni-cronos-7216',
    storageBucket: 'uni-cronos-7216.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Pey3pCdfbuP4eXNLh2fitlMifl-XAdY',
    appId: '1:604553621995:ios:5ef7a1637082083128e9ae',
    messagingSenderId: '604553621995',
    projectId: 'uni-cronos-7216',
    storageBucket: 'uni-cronos-7216.firebasestorage.app',
    iosBundleId: 'app.com.unicronos',
  );
}
